sudo: required
language: bash
services:
  - docker

install:
  - docker build -t jenkins-dind-nodejs .
  - docker run --name jenkins --privileged -d -p 127.0.0.1:8080:8080 -v /srv/jenkins:/var/jenkins_home jenkins-dind-nodejs:latest

script:
  - docker ps | grep -q jenkins
  - docker exec jenkins docker ps | grep -q CONTAINER
  - docker exec jenkins node -v | grep -q v
  - docker exec jenkins npm -v | grep -q v
  - sleep 30 && curl -slI http://127.0.0.1:8080 | grep -q "HTTP/1.1 403"
  
